### ISSUE TITLE
PHP Startup: Invalid library 

### ISSUE THREAD

**Issue by tohidplus** [arnaud-lb/php-go#9]
This is my php file:
```php
<?php
$module = phpgo_load("example.so", "example");
echo $module->toUpper('foo');
```

When I run the command 
```bash
php  index.php 
```
I got this error
```bash
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) '/usr/lib/php/20170718/example.so' in Unknown on line 0
PHP Fatal error:  Uncaught Error: Call to undefined function toUpper() in /home/tohid/go/src/gotutorial/extension/index.php:2
Stack trace:
#0 {main}
  thrown in /home/tohid/go/src/gotutorial/extension/index.php on line 2
```

**Comment by dignfei** [comment]
> This is my php file:
> 
> ```
> <?php
> $module = phpgo_load("example.so", "example");
> echo $module->toUpper('foo');
> ```
> 
> When I run the command
> 
> ```shell
> php  index.php 
> ```
> 
> I got this error
> 
> ```shell
> PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) '/usr/lib/php/20170718/example.so' in Unknown on line 0
> PHP Fatal error:  Uncaught Error: Call to undefined function toUpper() in /home/tohid/go/src/gotutorial/extension/index.php:2
> Stack trace:
> #0 {main}
>   thrown in /home/tohid/go/src/gotutorial/extension/index.php on line 2
> ```

没有设置好路径
